#!/bin/bash
cleanup_PATH() {
  PATH="$(printf %s "$PATH" \
    | awk -v RS=: -v ORS= '!a[$0]++ { if (NR>1) print ":"; print $0 }')"
  export PATH
}

trap cleanup_PATH RETURN
PATH="\
${HOME}/bin:\
${HOME}/.cargo/bin:\
${HOME}/.local/bin:\
${HOME}/.bun/bin:\
${HOME}/.local/share/fnm:\
${HOME}/.local/share/flatpak/exports/bin:\
/var/lib/flatpak/exports/bin:\
${HOME}/.local/share/JetBrains/Toolbox/scripts:\
${PATH}:\
/sbin:\
/usr/sbin:\
${HOME}/go/bin"

[[ "$OSTYPE" == linux-gnu && -x /home/linuxbrew/.linuxbrew/bin/brew ]] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

if ! command -v nix >/dev/null; then
  [[ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]] && \
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  [[ -e "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]] && \
    . "${HOME}"'/.nix-profile/etc/profile.d/nix.sh'
fi

command -v fnm >/dev/null && eval "$(fnm env)"
command -v direnv >/dev/null && eval "$(direnv hook bash)"

if [[ "$TERM_PROGRAM" = vscode ]]; then
  export EDITOR='code --wait'
elif command -v vim >/dev/null; then
  export EDITOR=vim
else
  export EDITOR=vi
fi

[[ $- != *i* ]] && return

HISTSIZE=4000
HISTFILESIZE=-1
HISTCONTROL=ignoreboth
unset MAILCHECK
shopt -s checkwinsize
shopt -s direxpand 2>/dev/null || :
shopt -s histappend
shopt -s no_empty_cmd_completion
set -o noclobber
export QUOTING_STYLE=literal
alias ls='ls -FHh --color'
alias userctl='systemctl --user'
alias juserctl='journalctl --user'
alias gdb='gdb -q'
alias rsync='rsync \
  --recursive \
  --sparse \
  --preallocate \
  --progress \
  --partial \
  --human-readable \
  --fsync'
alias tf=terraform

ps1_host='\h'
[[ -n $CONTAINER_ID ]] && ps1_host="$CONTAINER_ID"
PS1='\[\e]0;\u@'"$ps1_host"':\w\a\]'
[[ -n $SSH_CLIENT || -n $container && $container != 'flatpak' ]] && PS1="$PS1"'\u@'"$ps1_host"' '
PS1="$PS1"'$([[ -n "$(jobs -p)" ]] && echo -n "%\j ")'
precmd() {
    local exit=$?
    ps1_status=
    [[ $exit -ne 0 ]] && ps1_status="${exit} "
}
PROMPT_COMMAND="precmd; ${PROMPT_COMMAND}"
PS1="$PS1"'$ps1_status\w \$ '

. /usr/share/bash-completion/bash_completion 2>/dev/null || :
