# background_opacity = 0.98

[colors]
draw_bold_text_with_bright_colors = false

# XTerm's default colors

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#cd0000'
green   = '#00cd00'
yellow  = '#cdcd00'
blue    = '#0000ee'
magenta = '#cd00cd'
cyan    = '#00cdcd'
white   = '#e5e5e5'

# Bright colors
[colors.bright]
black   = '#7f7f7f'
red     = '#ff0000'
green   = '#00ff00'
yellow  = '#ffff00'
blue    = '#5c5cff'
magenta = '#ff00ff'
cyan    = '#00ffff'
white   = '#ffffff'

[env]
WINIT_HIDPI_FACTOR = "96"

[font]
size = 9.5

[font.normal]
family = "DejaVu Sans Mono"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[window.dimensions]
columns = 95
lines = 24
