[window]
opacity = 0.91
resize_increments = true
dimensions = { columns = 100, lines = 25 }

[scrolling]
multiplier = 1

[font]
size = 10.1

[font.normal]
family = "Iosevka Term"

[colors.primary]
background = "#000000"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { mods = "Control | Shift", key = "N", action = "CreateNewWindow" },
]
