[misc]
pre_sudo = true
disable = ["node", "chezmoi", "emacs", "toolbx"]
ignore_failures = ["uv"]
# remote_topgrades = ["toothless", "pi", "parnas"]
# remote_topgrade_path = ".cargo/bin/topgrade"
assume_yes = false
no_retry = true
# Cleanup temporary or old files (default: false)
cleanup = true

# [commands]
# "Python Environment" = "~/dev/.env/bin/pip install -i https://pypi.python.org/simple -U --upgrade-strategy eager jupyter"
# "Custom command using interactive shell (unix)" = "-i vim_upgrade"

[brew]
# Execute `brew autoremove` after the step.
# autoremove = true
# Upgrade formulae built from the HEAD branch; `brew upgrade --fetch-HEAD`
# fetch_head = true


[linux]
# dnf_arguments = "--refresh"
# enable_tlmgr = true
# redhat_distro_sync = false

nix_arguments = "--impure"

[firmware]
# Offer to update firmware; if false just check for and display available updates
upgrade = true
